name: Release per language
on:
  push:
    tags:
      - "v*-fr"
      - "v*-en"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect language and version
        id: meta
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ "$TAG" =~ -fr$ ]]; then
            echo "lang=fr" >> $GITHUB_OUTPUT
            echo "flag=🇫🇷" >> $GITHUB_OUTPUT
            echo "dir=templates-FR" >> $GITHUB_OUTPUT
          elif [[ "$TAG" =~ -en$ ]]; then
            echo "lang=en" >> $GITHUB_OUTPUT
            echo "flag=🇬🇧" >> $GITHUB_OUTPUT
            echo "dir=templates-EN" >> $GITHUB_OUTPUT
          else
            echo "Unsupported tag suffix"; exit 1
          fi
          BASE="${TAG%-fr}"; BASE="${BASE%-en}"
          echo "base_ver=$BASE" >> $GITHUB_OUTPUT

      - name: Build ZIP
        run: |
          ZIP="template4JoplinTemplates-${{ steps.meta.outputs.base_ver }}-${{ steps.meta.outputs.lang }}.zip"
          zip -r "$ZIP" "${{ steps.meta.outputs.dir }}" README.md LICENSE
          echo "ZIP=$ZIP" >> $GITHUB_ENV

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.meta.outputs.base_ver }} ${{ steps.meta.outputs.flag }}
          generate_release_notes: true
          files: |
            ${{ env.ZIP }}
